name: Flask CI Pipeline

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
# The pipeline automatically validates code before and after merging into the main branch.

jobs:
  test:
    runs-on: ubuntu-latest
    # Jobs run on isolated Linux servers provided by GitHub Actions.

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        # This step pulls the latest version of the code into the CI environment.

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"
        # This ensures a consistent Python environment across all builds.

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install flask pytest
        # Core dependencies are installed directly in the CI pipeline.

      - name: Run tests
        run: |
          pytest
        # This step acts as a quality gate that prevents faulty code from being merged.

  docker-build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Build Docker image
        run: docker build -t my-app .




        


        

      # “This CI pipeline automatically builds the Flask application, installs dependencies,
      #   and runs automated tests on every push or pull request to the main branch.”